<a href="https://colab.research.google.com/github/Kstyle0710/my_numpy/blob/master/colab_np1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. np array 생성

In [3]:
## 1차원 배열
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [4]:
## 2차원 배열
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0][1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2


In [5]:
## 3차원 배열
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a3)
print(type(a3))
print(a3.shape)
print(a3[0][1])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(3, 2, 3)
[4 5 6]


# 2. 배열 생성 및 초기화

In [6]:
np.zeros(10)    # 모든 요소를 0으로 초기화

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3, 3))     # 모든 요소를 1으로 초기화

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.full((3,3), "15")   # 틀을 잡고 초기화 값 지정

array([['15', '15', '15'],
       ['15', '15', '15'],
       ['15', '15', '15']], dtype='<U2')

In [9]:
np.eye(5)    # 정사각형인 단위행렬 생성

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.tri(5)    # 삼각행렬 생성

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [11]:
## 생성한 값으로 배열 생성

In [12]:
np.arange(0, 30, 2)     ## 정수 범위로 배열 생성

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [13]:
np.linspace(0, 1, 5)   # 범위 내에서 균등 간격으로 배열 생성

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.logspace(0.1, 1, 20)    # 범위 내 균등 간격 배열 생성하되, 로그 스케일로 생성

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [15]:
np.random.random((5, 5))   # 랜덤한 실수의 배열 생성.. 튜플로 형태만 지정

array([[0.07026651, 0.71904471, 0.83276085, 0.51928131, 0.54897789],
       [0.10053049, 0.80984699, 0.59345456, 0.79389895, 0.26811328],
       [0.39456693, 0.03434597, 0.8730384 , 0.51919752, 0.25987018],
       [0.12939158, 0.41888078, 0.7231805 , 0.8543403 , 0.60103513],
       [0.58844885, 0.02509231, 0.02168046, 0.45290472, 0.88508271]])

In [16]:
np.random.randint(0, 10, (5, 5))   # 랜덤한 정수의 배열 생성.. 램덤 정수 범위 지정후 배열 형태 지정

array([[7, 2, 0, 1, 9],
       [6, 0, 7, 9, 4],
       [2, 4, 1, 5, 3],
       [4, 0, 3, 7, 2],
       [5, 1, 9, 0, 8]])

In [17]:
np.random.normal(0, 1, (3, 3))   # 정규분포를 고려한 랜덤한 수의 배열 생성

array([[ 0.69225083, -1.10924106, -0.83850178],
       [-1.40497462, -1.15567437, -2.05472305],
       [ 0.75444345,  0.19885393, -0.89246904]])

In [18]:
np.random.rand(5, 5)    # 균등분포를 고려한 랜덤한 수의 배열 생성 (배열 형태만 지정)

array([[0.35454434, 0.86222985, 0.69830191, 0.77087467, 0.65201999],
       [0.67592009, 0.91929356, 0.75110463, 0.62170651, 0.03449251],
       [0.70044676, 0.64804161, 0.45688488, 0.09858173, 0.7809074 ],
       [0.21340365, 0.0304152 , 0.90812797, 0.19727963, 0.71537932],
       [0.8766074 , 0.2411494 , 0.92837734, 0.31679802, 0.72745341]])

In [19]:
np.random.randn(5, 5)   # 표준정규분포를 고려한 랜덤한 수의 배열 생성

array([[ 0.85611001, -0.09485818, -0.23437064,  1.07098597,  0.68864309],
       [ 0.3542115 ,  0.99862613, -0.18857615,  0.74645979,  0.79608558],
       [ 0.46470092, -0.85396841, -0.28004354,  1.05346335,  2.11821574],
       [ 0.85304576, -0.37958887, -1.9334114 , -0.11363907,  0.65971006],
       [ 0.56133534, -0.29292207,  0.15725065,  0.10590952, -0.59105554]])

# 3. 표준 데이터 타입

In [20]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [22]:
np.full((3, 3), 1.25, dtype=float)

array([[1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25]])

# 4. 날짜 및 시간 배열 생성

In [23]:
date = np.array('2020-12-07', dtype=np.datetime64)
date

array('2020-12-07', dtype='datetime64[D]')

In [24]:
date + np.arange(12)

array(['2020-12-07', '2020-12-08', '2020-12-09', '2020-12-10',
       '2020-12-11', '2020-12-12', '2020-12-13', '2020-12-14',
       '2020-12-15', '2020-12-16', '2020-12-17', '2020-12-18'],
      dtype='datetime64[D]')

In [25]:
datetime = np.datetime64('2020-12-07 09:00')
datetime

numpy.datetime64('2020-12-07T09:00')

In [26]:
datetime = np.datetime64('2020-12-07 09:00:12.455', 'ns')    # 나노초는 맨뒤에 'ns' 추가
datetime

numpy.datetime64('2020-12-07T09:00:12.455000000')

# 5. 배열 속성 정보 조회

In [27]:
def array_info(a):
  print(a)
  print("ndim:", a.ndim)
  print("shape:", a.shape)
  print("dtype:", a.dtype)
  print("size:", a.size)
  print("itemsize:", a.itemsize)    # 값 하나가 차지하는 바이트
  print("nbytes:", a.nbytes)
  print("strides:", a.strides)    # 다음 값 다음 차원으로 넘어가기 위해 필요한 바이트

In [28]:
array_info(a1)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [29]:
array_info(a2)

[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
dtype: int64
size: 6
itemsize: 8
nbytes: 48
strides: (24, 8)


In [30]:
array_info(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
ndim: 3
shape: (3, 2, 3)
dtype: int64
size: 18
itemsize: 8
nbytes: 144
strides: (48, 24, 8)


# 6. 인덱싱

In [31]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-3])

[1 2 3 4 5]
1
3
5
3


In [32]:
print(a2)
print(a2[0, 1])
print(a2[1, 1])
print(a2[-1, 2])
print(a2[1][-1])

[[1 2 3]
 [4 5 6]]
2
5
6
6


# 7. 슬라이싱

슬라이싱 구문 : a[ start : stop : step] <br>
기본값 : start=0, stop=ndim, step=1

In [33]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[:2])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1]
[1 2]
[1 3 5]
[5 4 3 2 1]


In [34]:
## 블리언 인덱싱
print(a1)
bi = [False, True, True, False, False]
print(a1[bi])     # 블리언 인덱싱이 True인 것만 출력

[1 2 3 4 5]
[2 3]


In [35]:
print(a2)
bi = np.random.randint(0, 2, (2, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]]
[[False  True  True]
 [ True  True  True]]
[2 3 4 5 6]


In [36]:
## fancy indexing
print(a1)
print([a1[0], a1[2]])
idx = [0, 2]
print(a1[idx])

[1 2 3 4 5]
[1, 3]
[1 3]


In [37]:
print(a1)                   # 1차원 배열에
print([a1[0], a1[2]])
idx = np.array([[0, 1], [2, 0]])   # 2차원 인덱싱을 적용하는 경우
print(a1[idx])                 # 2차원 배열의 형태로 출력된다.

[1 2 3 4 5]
[1, 3]
[[1 2]
 [3 1]]


In [38]:
print(a2)
row = np.array([0,1])
col = np.array([1,2])
print(a2[row, col])

[[1 2 3]
 [4 5 6]]
[2 6]


# 8. 배열 값 삽입/수정/삭제/복사


*   insert() : 배열의 특정 위치에 값 삽입
*   axis를 지정하지 않으면 1차원 배열로 변환
*   추가할 방향을 axis로 지정
*   원본 배열 변경없이 새로운 배열 반환





In [39]:
print(a1)
b1 = np.insert(a1, 0, 10)
print(b1)
print(a1)  # a1 원본 값이 변경된 것은 아니다.

[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]


In [40]:
print(a2)
b2 = np.insert(a2, 1, 10, axis=0)
print(b2)
c2 = np.insert(a2, 1, 10, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]]
[[ 1 10  2  3]
 [ 4 10  5  6]]


In [41]:
# 인덱싱으로 접근하여 값 수정 가능
print(a1)
a1[0] = 77
print(a1)
a1[2:4] =  88
print(a1)

[1 2 3 4 5]
[77  2  3  4  5]
[77  2 88 88  5]


In [42]:
print(a1)
b1 = np.delete(a1, 1)
print(b1)
print(a1)

[77  2 88 88  5]
[77 88 88  5]
[77  2 88 88  5]


In [43]:
print(a2)
b2 = np.delete(a2, 1, axis=0)
print(b2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]]


In [44]:
print(a2)
print("------------")
a2_sub_copy = a2[:2, :2].copy()   # 별개의 메모리에 복사
print(a2_sub_copy)
a2_sub_copy[:, 1] = 1
print(a2_sub_copy)
print(a2)

[[1 2 3]
 [4 5 6]]
------------
[[1 2]
 [4 5]]
[[1 1]
 [4 1]]
[[1 2 3]
 [4 5 6]]


In [46]:
## 배열 전치
print(a2)
print(a2.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [48]:
print(a3)
print("---------------")
print(a3.T)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
---------------
[[[1 1 1]
  [4 4 4]]

 [[2 2 2]
  [5 5 5]]

 [[3 3 3]
  [6 6 6]]]


In [50]:
## 배열 재구조화 : reshape()
n1 = np.arange(1, 10)
print(n1)
print(n1.reshape(3, 3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
## 배열의 크기 변경 : resize
n2 = np.random.randint(0, 10, (2, 5))
print(n2)
n2.resize((5, 2))
print(n2)

[[2 2 3 8 8]
 [3 2 1 6 0]]
[[2 2]
 [3 8]
 [8 3]
 [2 1]
 [6 0]]


In [52]:
n3 = np.random.randint(0, 10, (2, 5))
print(n3)
n3.resize((10, 5))   # 더 큰 사이즈로 변경
print(n3)

[[2 0 1 2 1]
 [0 0 5 9 2]]
[[2 0 1 2 1]
 [0 0 5 9 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [54]:
n4 = np.random.randint(0, 10, (2, 5))
print(n4)
n4.resize((2, 2))   # 더 작은 사이즈로 변경
print(n4)

[[1 0 5 3 3]
 [2 3 3 0 6]]
[[1 0]
 [5 3]]


In [64]:
## 배열 추가 append()
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
b2 = np.arange(11, 20).reshape(3, 3)
print(b2)
c2 = np.append(a2, b2)      ## axis 지정이 없으면 결과가 1차원 배열 형태로 바뀜
print(c2)
d2 = np.append(a2, b2, axis=0)
print(d2)
e2 = np.append(a2, b2, axis=1)
print(e2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[ 1  2  3  4  5  6  7  8  9 11 12 13 14 15 16 17 18 19]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [66]:
## 배열 연결 concatenate()
a1 = np.array([1, 2, 3])
b1 = np.array([4, 5, 6])
np.concatenate([a1, b1])

array([1, 2, 3, 4, 5, 6])

In [68]:
## 배열 분할 :split(), vsplit(), hsplit()...
a1 = np.arange(0, 10)
print(a1)
b1, c1 = np.split(a1, [5])    ## 한개가 둘로 분할되었기 때문에 변수 두개에 담아준다.
print(b1, c1)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]


In [72]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print("-------------")
b2, c2 = np.vsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


In [73]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print("-------------")
b2, c2 = np.hsplit(a2, [2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


# 9. 배열 연산

In [75]:
a1 = np.array([1, 2, 3])
print(a1)
b1 = a1 + 6      # 6을 각 값별로 적용해주지 않아도 알아서 적용되서 계산된다. (브로드캐스팅)
print(b1)

[1 2 3]
[7 8 9]


In [82]:
a1 = np.array([1, 2, 3])
print(a1)
b1 = np.array([1, 2, 3]).reshape(3, 1)
print(b1)
c1 = a1 + b1    # 브로드캐스팅의 결과로 3 by 3 배열이 나온다.
print(c1)

[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [88]:
a1 = np.array([7, 8, 9])
print(a1/3)
print(a1//3)   # 나눗셈 내림
print(a1%3)

[2.33333333 2.66666667 3.        ]
[2 2 3]
[1 2 0]


# 10. 집계 함수

In [93]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0))  # 세로로 더하기
print(a2.sum(axis=1))  # 가로로 더하기

[[7 2 4]
 [1 7 3]
 [6 4 9]]
43 43
[14 13 16]
[13 11 19]


In [94]:
print(a2)
print(np.cumsum(a2))
print(a2.cumsum(axis=0)) 
print(np.cumsum(a2, axis=1))  

[[7 2 4]
 [1 7 3]
 [6 4 9]]
[ 7  9 13 14 21 24 30 34 43]
[[ 7  2  4]
 [ 8  9  7]
 [14 13 16]]
[[ 7  9 13]
 [ 1  8 11]
 [ 6 10 19]]


In [96]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0))  
print(np.diff(a2, axis=1))  

[[7 2 4]
 [1 7 3]
 [6 4 9]]
[[-5  2]
 [ 6 -4]
 [-2  5]]
[[-6  5 -1]
 [ 5 -3  6]]
[[-5  2]
 [ 6 -4]
 [-2  5]]


In [97]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis=0))
print(np.mean(a2, axis=1))

[[7 2 4]
 [1 7 3]
 [6 4 9]]
4.777777777777778
[4.66666667 4.33333333 5.33333333]
[4.33333333 3.66666667 6.33333333]


In [98]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis=0))
print(np.std(a2, axis=1))

[[7 2 4]
 [1 7 3]
 [6 4 9]]
2.4845199749997664
[2.62466929 2.05480467 2.62466929]
[2.05480467 2.49443826 2.05480467]


In [102]:
a2 = np.random.randint(1, 10, size=(3, 3))
print(a2)
print(np.argmin(a2))    # 최소값 자체가 아닌, 최소값의 인덱스 출력
print(np.argmin(a2, axis=0))
print(np.argmin(a2, axis=1))

[[2 9 9]
 [1 6 5]
 [1 5 1]]
3
[1 2 2]
[0 0 0]


In [103]:
a2 = np.array([[False, False, True],
               [False, True, True],
               [False, True, True]])
print(a2)
print(np.any(a2))
print(np.any(a2, axis=0))
print(np.any(a2, axis=1))


[[False False  True]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[ True  True  True]


In [104]:
a1 = np.arange(1, 10)
print(a1)
print(a1 == 5)

[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]


In [105]:
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2>5))
print(np.sum(a2>5))
print(np.sum(a2>5, axis=0))
print(np.sum(a2>5, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]


In [107]:
a1 = np.array([1, 2, 3, 4, 5])
b1 = np.array([3, 4, 3, 3, 4])
print(np.isclose(a1, b1))

[False False  True False False]
