<a href="https://colab.research.google.com/github/Kstyle0710/my_numpy/blob/master/colab_np1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1. np array 생성

In [18]:
## 1차원 배열
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
print(a1.shape)
print(a1[0])

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


In [17]:
## 2차원 배열
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print(type(a2))
print(a2.shape)
print(a2[0][1])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2


In [16]:
## 3차원 배열
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a3)
print(type(a3))
print(a3.shape)
print(a3[0][1])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
(3, 2, 3)
[4 5 6]


# 2. 배열 생성 및 초기화

In [2]:
np.zeros(10)    # 모든 요소를 0으로 초기화

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3, 3))     # 모든 요소를 1으로 초기화

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
np.full((3,3), "15")   # 틀을 잡고 초기화 값 지정

array([['15', '15', '15'],
       ['15', '15', '15'],
       ['15', '15', '15']], dtype='<U2')

In [10]:
np.eye(5)    # 정사각형인 단위행렬 생성

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.tri(5)    # 삼각행렬 생성

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [24]:
## 생성한 값으로 배열 생성

In [26]:
np.arange(0, 30, 2)     ## 정수 범위로 배열 생성

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [27]:
np.linspace(0, 1, 5)   # 범위 내에서 균등 간격으로 배열 생성

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [28]:
np.logspace(0.1, 1, 20)    # 범위 내 균등 간격 배열 생성하되, 로그 스케일로 생성

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [29]:
np.random.random((5, 5))   # 랜덤한 실수의 배열 생성.. 튜플로 형태만 지정

array([[0.37943176, 0.4174978 , 0.15295474, 0.01560562, 0.57861972],
       [0.4886627 , 0.44745752, 0.73017305, 0.61460916, 0.73531184],
       [0.42641849, 0.39912793, 0.44779777, 0.23447379, 0.53557477],
       [0.70312157, 0.90418084, 0.90915487, 0.02774321, 0.28085696],
       [0.82443155, 0.25656289, 0.21955591, 0.35403267, 0.021143  ]])

In [30]:
np.random.randint(0, 10, (5, 5))   # 랜덤한 정수의 배열 생성.. 램덤 정수 범위 지정후 배열 형태 지정

array([[8, 3, 3, 2, 4],
       [3, 3, 6, 6, 0],
       [9, 7, 9, 2, 1],
       [4, 1, 3, 5, 9],
       [8, 4, 9, 3, 0]])

In [32]:
np.random.normal(0, 1, (3, 3))   # 정규분포를 고려한 랜덤한 수의 배열 생성

array([[-0.25937026,  1.2535737 , -0.46727206],
       [-0.94067096, -0.2298729 , -2.20505874],
       [ 0.57926241, -0.1409718 , -0.01338525]])

In [37]:
np.random.rand(5, 5)    # 균등분포를 고려한 랜덤한 수의 배열 생성 (배열 형태만 지정)

array([[0.72933367, 0.10812457, 0.05522505, 0.64455036, 0.54609067],
       [0.26483211, 0.88253355, 0.01171481, 0.97449614, 0.26103662],
       [0.65922853, 0.96861306, 0.9309611 , 0.41855515, 0.3170308 ],
       [0.21709201, 0.67100211, 0.46888744, 0.81521596, 0.05432422],
       [0.72533104, 0.40062041, 0.08182717, 0.38586392, 0.01318632]])

In [38]:
np.random.randn(5, 5)   # 표준정규분포를 고려한 랜덤한 수의 배열 생성

array([[ 5.04074856e-01,  3.53878091e-02,  6.77748219e-01,
         2.62567405e-01,  7.40090648e-01],
       [ 4.86856644e-01,  4.24260956e-01, -1.62917514e+00,
        -6.33298397e-04,  2.15820689e-01],
       [ 8.38442908e-01,  2.85536723e-02, -1.42493582e+00,
         1.57019588e+00, -2.73626277e-01],
       [ 4.12545881e-01,  1.25582481e+00, -9.54743991e-01,
         1.10956564e+00, -9.68101497e-01],
       [ 3.89617461e-01, -7.24097824e-01,  4.69791844e-01,
         3.53987168e-01, -6.08422783e-01]])

# 3. 표준 데이터 타입

In [39]:
np.zeros(20, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [40]:
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [42]:
np.full((3, 3), 1.25, dtype=float)

array([[1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25]])

# 4. 날짜 및 시간 배열 생성

In [44]:
date = np.array('2020-12-07', dtype=np.datetime64)
date

array('2020-12-07', dtype='datetime64[D]')

In [45]:
date + np.arange(12)

array(['2020-12-07', '2020-12-08', '2020-12-09', '2020-12-10',
       '2020-12-11', '2020-12-12', '2020-12-13', '2020-12-14',
       '2020-12-15', '2020-12-16', '2020-12-17', '2020-12-18'],
      dtype='datetime64[D]')

In [46]:
datetime = np.datetime64('2020-12-07 09:00')
datetime

numpy.datetime64('2020-12-07T09:00')

In [50]:
datetime = np.datetime64('2020-12-07 09:00:12.455', 'ns')    # 나노초는 맨뒤에 'ns' 추가
datetime

numpy.datetime64('2020-12-07T09:00:12.455000000')

# 5. 배열 속성 정보 조회

In [51]:
def array_info(a):
  print(a)
  print("ndim:", a.ndim)
  print("shape:", a.shape)
  print("dtype:", a.dtype)
  print("size:", a.size)
  print("itemsize:", a.itemsize)    # 값 하나가 차지하는 바이트
  print("nbytes:", a.nbytes)
  print("strides:", a.strides)    # 다음 값 다음 차원으로 넘어가기 위해 필요한 바이트

In [52]:
array_info(a1)

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
itemsize: 8
nbytes: 40
strides: (8,)


In [53]:
array_info(a2)

[[1 2 3]
 [4 5 6]]
ndim: 2
shape: (2, 3)
dtype: int64
size: 6
itemsize: 8
nbytes: 48
strides: (24, 8)


In [54]:
array_info(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
ndim: 3
shape: (3, 2, 3)
dtype: int64
size: 18
itemsize: 8
nbytes: 144
strides: (48, 24, 8)


# 6. 인덱싱

In [55]:
print(a1)
print(a1[0])
print(a1[2])
print(a1[-1])
print(a1[-3])

[1 2 3 4 5]
1
3
5
3


In [62]:
print(a2)
print(a2[0, 1])
print(a2[1, 1])
print(a2[-1, 2])
print(a2[1][-1])

[[1 2 3]
 [4 5 6]]
2
5
6
6


# 7. 슬라이싱

슬라이싱 구문 : a[ start : stop : step] <br>
기본값 : start=0, stop=ndim, step=1

In [66]:
print(a1)
print(a1[0:2])
print(a1[0:])
print(a1[:1])
print(a1[:2])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1]
[1 2]
[1 3 5]
[5 4 3 2 1]


In [68]:
## 블리언 인덱싱
print(a1)
bi = [False, True, True, False, False]
print(a1[bi])     # 블리언 인덱싱이 True인 것만 출력

[1 2 3 4 5]
[2 3]


In [70]:
print(a2)
bi = np.random.randint(0, 2, (2, 3), dtype=bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]]
[[ True  True False]
 [ True False False]]
[1 2 4]


In [72]:
## fancy indexing
print(a1)
print([a1[0], a1[2]])
idx = [0, 2]
print(a1[idx])

[1 2 3 4 5]
[1, 3]
[1 3]


In [74]:
print(a1)                   # 1차원 배열에
print([a1[0], a1[2]])
idx = np.array([[0, 1], [2, 0]])   # 2차원 인덱싱을 적용하는 경우
print(a1[idx])                 # 2차원 배열의 형태로 출력된다.

[1 2 3 4 5]
[1, 3]
[[1 2]
 [3 1]]


In [77]:
print(a2)
row = np.array([0,1])
col = np.array([1,2])
print(a2[row, col])

[[1 2 3]
 [4 5 6]]
[2 6]


# 8. 배열 값 삽입/수정/삭제/복사